import { randomBytes } from 'crypto';

/**
 * Interface for Hardware Security Module (HSM) operations.
 * This abstracts the interaction with a physical or cloud HSM.
 */
export interface HSMClient {
  /**
   * Signs data using a key stored within the HSM.
   * @param keyId The identifier for the key in the HSM.
   * @param data The data to be signed (e.g., a JWT payload).
   * @returns A promise that resolves with the signature.
   */
  sign(keyId: string, data: string): Promise<string>;

  /**
   * Verifies a signature using a key stored within the HSM.
   * @param keyId The identifier for the key in the HSM.
   * @param data The original data that was signed.
   * @param signature The signature to verify.
   * @returns A promise that resolves to true if the signature is valid, false otherwise.
   */
  verify(keyId: string, data: string, signature: string): Promise<boolean>;
}

/**
 * A mock HSM client for development and testing purposes.
 * In a real scenario, this would interact with a cloud HSM service (e.g., AWS CloudHSM, Google Cloud HSM).
 */
export class MockHSMClient implements HSMClient {
  private mockSignatures: Map<string, string> = new Map(); // Stores mock signatures for verification

  async sign(keyId: string, data: string): Promise<string> {
    // In a real HSM, this would involve a cryptographic signing operation.
    // Here, we just create a deterministic mock signature.
    const mockSignature = `mock-hsm-signature-${keyId}-${randomBytes(16).toString('hex')}`;
    this.mockSignatures.set(mockSignature, data); // Store data associated with signature for mock verification
    console.log(`[MockHSM] Signing data with key ${keyId}. Mock signature: ${mockSignature}`);
    return mockSignature;
  }

  async verify(keyId: string, data: string, signature: string): Promise<boolean> {
    // In a real HSM, this would involve a cryptographic verification operation.
    // Here, we check if the mock signature was generated by this mock client for this data.
    const originalData = this.mockSignatures.get(signature);
    const isValid = originalData === data;
    console.log(`[MockHSM] Verifying signature for key ${keyId}. Signature: ${signature}, Valid: ${isValid}`);
    return isValid;
  }
}