# AfriPay Universal - Prometheus Configuration
# Monitoring configuration for all microservices

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'afripay-dev'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rule files
rule_files:
  # - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Identity Service
  - job_name: 'identity-service'
    static_configs:
      - targets: ['identity-service:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: identity-service:8000

  # Biometric Service
  - job_name: 'biometric-service'
    static_configs:
      - targets: ['biometric-service:8001']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  # Transaction Service (Spring Boot Actuator)
  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:8002']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  # Wallet Service
  - job_name: 'wallet-service'
    static_configs:
      - targets: ['wallet-service:8003']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  # USSD Gateway
  - job_name: 'ussd-gateway'
    static_configs:
      - targets: ['ussd-gateway:8004']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  # Agent Service
  - job_name: 'agent-service'
    static_configs:
      - targets: ['agent-service:8005']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # MongoDB Exporter
  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # RabbitMQ Exporter
  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # NGINX Exporter
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # Docker container metrics via cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # Blackbox exporter for external endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://identity-service:8000/health
        - http://biometric-service:8001/health
        - http://transaction-service:8002/actuator/health
        - http://wallet-service:8003/health
        - http://ussd-gateway:8004/health
        - http://agent-service:8005/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom application metrics
  - job_name: 'afripay-business-metrics'
    static_configs:
      - targets: 
        - 'transaction-service:8002'
        - 'wallet-service:8003'
    metrics_path: /business-metrics
    scrape_interval: 60s
    scrape_timeout: 30s
    honor_labels: true
    params:
      format: ['prometheus']

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Remote write configuration (for production)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"

# Recording rules for better performance
# These create pre-computed metrics
recording_rules:
  - name: afripay.rules
    rules:
      # Transaction rate per minute
      - record: afripay:transaction_rate_1m
        expr: rate(transactions_total[1m])
        labels:
          service: "transaction"
          
      # API request rate per service
      - record: afripay:api_request_rate_5m
        expr: rate(http_requests_total[5m])
        
      # Error rate percentage
      - record: afripay:error_rate_5m
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100
        
      # Average response time
      - record: afripay:response_time_avg_5m
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])
        
      # Database connection pool utilization
      - record: afripay:db_pool_utilization
        expr: (db_connections_active / db_connections_max) * 100
        
      # Memory utilization per service
      - record: afripay:memory_utilization
        expr: (process_resident_memory_bytes / container_spec_memory_limit_bytes) * 100
        
      # CPU utilization per service
      - record: afripay:cpu_utilization
        expr: rate(process_cpu_seconds_total[5m]) * 100

# Alerting rules
alerting_rules:
  - name: afripay.alerts
    rules:
      # Service down alert
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.instance }} is down"
          description: "{{ $labels.instance }} has been down for more than 1 minute"
          
      # High error rate alert
      - alert: HighErrorRate
        expr: afripay:error_rate_5m > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }}% for {{ $labels.service }}"
          
      # High response time alert
      - alert: HighResponseTime
        expr: afripay:response_time_avg_5m > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "Average response time is {{ $value }}s for {{ $labels.service }}"
          
      # Database connection pool exhaustion
      - alert: DatabasePoolExhaustion
        expr: afripay:db_pool_utilization > 90
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "Connection pool utilization is {{ $value }}% for {{ $labels.instance }}"
          
      # High memory usage
      - alert: HighMemoryUsage
        expr: afripay:memory_utilization > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory utilization is {{ $value }}% for {{ $labels.instance }}"
          
      # High CPU usage
      - alert: HighCPUUsage
        expr: afripay:cpu_utilization > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU utilization is {{ $value }}% for {{ $labels.instance }}"
          
      # Disk space low
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Disk space is running low"
          description: "Disk usage is above 90% on {{ $labels.instance }}"
          
      # Transaction volume spike
      - alert: TransactionVolumeSpike
        expr: increase(afripay:transaction_rate_1m[5m]) > 1000
        for: 2m
        labels:
          severity: info
        annotations:
          summary: "Transaction volume spike detected"
          description: "Transaction rate has increased significantly: {{ $value }} transactions/minute"